### ISSUE TITLE
Consider special handling of Libre Office settings.xml file

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/sheets-preservation-spec#10]
The `settings.xml` files found in ODF documents may require special handling, or even removal(??). Things to considers:

- how universal is the use of such a file, test other creating applications:
  - [x] Excel (Doesn't create)
  - [x] Open Office
  - [x] Libre Office (Does create)
- the file itself is part of the `config` namespace and only provides a way of encoding "implementation specific settings", these aren't to any schema or specification and their interpretation depends on the rendering software.

**Comment by Asbjoedt** [comment]
I also tried the applications
- [ x ] ONLYOFFICE
creates a ```config:config-item-set``` called ```ooo:view-settings```.
creates attribute "ActiveTable" among others. Dees not created "EmbedFonts", "EmbedOnlyUsedFonts", "isDocumentShared" nor "Loadreadonly".
- [ x ] Calligra Sheets
creates a ```config:config-item-set``` called ```view-settings```.
Dees not created "ActiveTable", "EmbedFonts", "EmbedOnlyUsedFonts", "isDocumentShared" nor "Loadreadonly".
- [ x ] Gnumeric
creates two ```config:config-item-set``` called ```ooo:view-settings``` and  ```gnm:settings```.
creates attribute "ActiveTable" among others. Dees not created "EmbedFonts", "EmbedOnlyUsedFonts", "isDocumentShared" nor "Loadreadonly".
