### ISSUE TITLE
After removal of embedded objects, document associations

### ISSUE THREAD

**Issue by RvanVeenendaal** [openpreserve/sheets-preservation-spec#18]
In Table 5, at ODS_5, embedded objects may be converted to file formats and removed from the spreadsheet's preservation manifestation. If that happens, as a guideline we should probably make explicit that one probably wants to preserve the association between the spreadsheet and the objects that were originally embedded in it.
This is probably the same for OOXML.

**Comment by Asbjoedt** [comment]
Agree with Remco. The guideline for ODS_5 is very sparse and should be expanded.
