### ISSUE TITLE
In Table 5, ODS_7, macros could also change the original object

### ISSUE THREAD

**Issue by RvanVeenendaal** [openpreserve/sheets-preservation-spec#19]
At Table 5, ODS_7, macros are mentioned as a security risk. We could probably add that in an AIP, you probably don't want to have any macros that potentially change the content of the spreadsheet. A macro that uses today's date to update cells could result in a spreadsheet with a different content from what was originally ingested. So either macros should be removed (preserving the values the time of ingest, but removing something from the original object) or the execution of macros should be disabled (preservering the original object but also preserving the risk that the macros are re-enabled at a later time).
This is probably the same for OOXML.

**Comment by RvanVeenendaal** [comment]
Sorry, macros potentially changing spreadsheets is already mentioned in the specification. Issue closed.

**Comment by Asbjoedt** [comment]
I think this is excellent observations, and there is a dilemma involved with the macros. How to handle macros, and are we doing it the right way, is a good topic to discuss in a meeting.

**Comment by Asbjoedt** [comment]
I will read the guideline for macros again to make sure "macro disabled" but kept in sheet is covered in it.
