### ISSUE TITLE
Questions about the guidelines for mark-up language sheets

### ISSUE THREAD

**Issue by RvanVeenendaal** [openpreserve/sheets-preservation-spec#20]
In Table 7 under [5.3](https://github.com/opf-labs/sheets-preservation-spec/blob/main/v1.0/Specification.md#53-mark-up-languages), we may want to explain that it is probably good to preserve the associations between the individual sheets Sheet1, Sheet2, etc. in metadata or other documentation.

And why must these sheets be exported to files names sheet1.csv, sheet2,csv, etc., when they sometimes have been given (mnemonic) sheet names that one may want to preserve? Shouldn't the guidelines tell people to export to sheet1.csv, sheet2.csv, etc. unless the sheets have been given names? And if so, export using those names? 

When reviewing this issue, take into consideration the image material, exported to image file formats with 'image1', 'image2', etc., when they could also stem from named sheets.

**Comment by Asbjoedt** [comment]
I think your idea about naming the .csv files according to their sheet name in the spreadsheet is better than what we currently recommend. The original purpose was to preserve the order of the sheets in the file names.

We could merge the two approaches by prefixing the files with a number like this:

Sheet 1 with name "data"
Sheet 2 with name "diagrams"

Becomes:
1_data.csv
2_diagrams.csv

I agree, we should imitate this for static images.

**Comment by carlwilson** [comment]
It may be trickier to reliably derive an ordinal for these sheets unless one is baked into the specification and XML attributes.

**Comment by Asbjoedt** [comment]
A related issue is how to handle hidden sheets. Should they be included in the preservation copy in csv and static file formats or not.

**Comment by carlwilson** [comment]
First up this is how a simple two sheeted spreadsheet presents itself within and ODF file:

```xml
<office:body>
    <office:spreadsheet>
        <table:calculation-settings table:automatic-find-labels="false" table:use-regular-expressions="false" table:use-wildcards="true"/>
        <table:table table:name="Sheet1" table:style-name="ta1">
            <table:table-column table:style-name="co1" table:default-cell-style-name="Default"/>
            <table:table-row table:style-name="ro1">
                <table:table-cell office:value-type="string" calcext:value-type="string">
                    <text:p>test</text:p>
                </table:table-cell>
            </table:table-row>
        </table:table>
        <table:table table:name="Sheet2" table:style-name="ta1">
            <table:table-column table:style-name="co1" table:default-cell-style-name="Default"/>
            <table:table-row table:style-name="ro1">
                <table:table-cell office:value-type="string" calcext:value-type="string">
                    <text:p>test</text:p>
                </table:table-cell>
            </table:table-row>
        </table:table>
        <table:named-expressions/>
    </office:spreadsheet>
</office:body>
```

Note that although the sheets are presented in order, there is no ordinal suggestion apart from the number that was assigned as part of the worksheet name.

> A related issue is how to handle hidden sheets. Should they be included in the preservation copy in csv and static file formats or not.

Hidden tables in ODF may be trickier than you think. There are XML elements to hide paragraphs, cells and cell-ranges, but nothing obvious for tables. A lot of the formatting is done via CSS which has it's own way of denoting hidden, and it's just a display attribute. @Asbjoedt if you could create an ODF spreadsheet with a hidden table as you're considering I'll be happy to take a look.

**Comment by Asbjoedt** [comment]
I will look at at the standard (again) to make sure, we can't trust the sheet order shown in an application.

**Comment by RvanVeenendaal** [comment]
I have taken a loot at the specification. There is nothing explicit about the order of sheets (tables) in a workbook (spreadsheet). 
A test with a spreadsheet with sheet1 and sheet2, saved in that order and saved in reverse order, demonstrates that the order in the contents.xml file _seems_ to imply presentation order in the app. So it _seems_ that the 'document order', for which the specification refers to the [XPATH Data Model] (https://www.w3.org/TR/1999/REC-xpath-19991116/#data-model) is used as presenting order in the app. But I don't think we can rely on all apps implementing this the same way.

In fact, Microsoft Excel OOXML files have a workbook.xml file inside, in which the order of the sheets seems to have been made explicit using sheetId and/or r:id (note: haven't looked at this specification): 
<sheets><sheet name="Blad1" sheetId="1" r:id="rId1"/><sheet name="Blad2" sheetId="2" r:id="rId2"/></sheets>

My advice to us: let's use the sheet names and presume nothing about the sheet order other than that we process it in the order in which we encounter them in the document.

**Comment by Asbjoedt** [comment]
Decision made on meeting 20th of June 2023:
There's no ordinal in the specification.
Applications typically render the order based on the XML order.
We decide not to use the order in the naming scheme, because the order in the XML is implicit, but we do consider there may be scenarios where the roder is significant to preserve. The solution is therefore to establish a metadata file and preserve the information here. We will look more into this.
