### ISSUE TITLE
Add requirement/guideline covering thumbnail previews for ODF documents

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/sheets-preservation-spec#24]
Taking into account this: <https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part2-packages/OpenDocument-v1.3-os-part2-packages.html#a_3_8_Preview_Image>

**Comment by Asbjoedt** [comment]
This issue is duplicate from https://github.com/openpreserve/sheets-preservation-spec/issues/7, but this issue is titled more action-oriented on creating the change, therefore I suggest we keep this issue as the real one and just delete the other one
